steps:
  # Build the .NET application
  - name: 'mcr.microsoft.com/dotnet/core/sdk:latest'
    entrypoint: 'dotnet'
    args: ['publish', '-c', 'Release', '-o', '$$BUILD_DIR/publish']
 
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--image-url=gcr.io/$PROJECT_ID/my-dotnet-app'
      - '--version=latest'
      - '--project=$PROJECT_ID'
      - '--quiet'
      - 'app.yaml'  # Replace with your app.yaml file name
    dir: '$$BUILD_DIR/publish'
